### ISSUE TITLE
less than 8 buttons in a screen

### ISSUE THREAD

**Issue by zakaos** [zakaos/opentxtgame#12]
I imagine there will be times, when less than 8 options will be required in a room. Theoritical solution for this would be to have the btntxt="" , and an if statement in the makeRoom function that sets any buttons that are equal to "" to set opacity to 0, or visibility to none, so that they can be hidden if they do not contain btntxt.

**Comment by jakesweb** [comment]
I'll take a look at this.

**Comment by zakaos** [comment]
Awesome! Thanks!
