### ISSUE TITLE
item objects system

### ISSUE THREAD

**Issue by zakaos** [zakaos/opentxtgame#18]
because items will be found in different rooms, and added to inventory, we should have a similar structure to the items as the rooms.
items will contain several properties::
title:"flashlight";
description: "there is a flashlight laying here.";
startingRoom:DiningRoom;
(or None, and it could be added to inventory through an event like :"you clean the room and you find a flashlight) 
hasItem=true;
(having a specific item would alter room descriptions, or add new buttons to a room)

**Comment by zakaos** [comment]
added basic item system, item spawning not working yet.

**Comment by hyeri0609** [comment]
I am not sure I understand this issue's scope, It seems to be a big issue. Is it possible to separate it into smaller issues?

**Comment by zakaos** [comment]
sure let me see what i can do, bout to go to work, ill take a look after
work on about 9 hours.

**Comment by zakaos** [comment]
closing issue, as basic item properties have been established.
