### ISSUE TITLE
create gui that builds rooms.

### ISSUE THREAD

**Issue by zakaos** [zakaos/opentxtgame#24]
create simple gui that lets users export games using the opentxtgame engine

**Comment by jakesweb** [comment]
Since the rooms are JSON we can use a web page that will allow them to input this stuff as field data and then output the JSON. For the buttons the input text would be a field but the function part should be radio buttons or a drop down that outputs pre-defined options.

**Comment by zakaos** [comment]
Ooooh, this will probably be easier than I thought! i didnt even think of the JSON functionality.

**Comment by hyeri0609** [comment]
Do you mind that a player manipulate data and then import back?

**Comment by hyeri0609** [comment]
mm..I think I asked wrong question, why do you need to export game?

**Comment by jakesweb** [comment]
You are correct, there is no need to export anything directly. It could just be that the JSON is stored in a file and the file is parsed directly. What I envision is that the page has multiple rooms that can be expanded out with the options and then are added to in that page.

**Comment by hyeri0609** [comment]
Yes, we might start on json and go further to nosql, totally agree on that.
and it would be great if we know what we want to see for final product precisely then we will design it to the right way

**Comment by zakaos** [comment]
ideally the final product would let somebody design a text game completely and export the needed files to a folder/zip. probably no way to do this with just js. maybe best to seperate this editor to a seperate repo

**Comment by hyeri0609** [comment]
ic, that makes it more clear for me, thank you. then i agree with @jcolborn-dropdeadgames to export as json and might also include html + css + images like you said in a zip folder
