### ISSUE TITLE
position footertxt @ bottom of maintxtwindow

### ISSUE THREAD

**Issue by zakaos** [zakaos/opentxtgame#25]
add css to position footertxt at bottom of maintxtwindow

**Comment by hyeri0609** [comment]
I've already checked 'Issue#19 Border on bottom of button window below viewable space on mobile', I am not familiar much with the way we freeze boxes on viewable area. May i ask, do you want to put image as background, like a room picture and picture of items that we can click? this will change everything on screen design.

**Comment by zakaos** [comment]
we could fork a project like that eventually, i want this basic engine to be entirely text based.
