### ISSUE TITLE
create inventory system

### ISSUE THREAD

**Issue by zakaos** [zakaos/opentxtgame#9]
create system of storing inventory, likely using an array

**Comment by hyeri0609** [comment]
will the inventory relate to account/or it will apply to all public users?

**Comment by zakaos** [comment]
Good question, I hadnt even thought of this as multiple users playing multiplayer. The inventory system is referring to simple inventory system where player has a simple array of items.

**Comment by hyeri0609** [comment]
oki, what about a class which you call add/remove/get methods to put/get stuffs (a string) from simple array?

**Comment by zakaos** [comment]
wow, that sounds perfect. You really eloquently described a perfect
solution, Thanks again! This is my first open source project, and im really
amazed by the willingness of people to help with this project, I really
cant say thanks enough

**Comment by hyeri0609** [comment]
oh, i thank you too ^ ^ for creating this project; i enjoy sharing ^ ^
and also gonna take this issue, you may assign to me

**Comment by zakaos** [comment]
so, its not letting me assign it to you, maybe cause im on mobile, will assign you when i get home.

**Comment by hyeri0609** [comment]
np ^ ^
...
oh, after quick check, i am not sure we can do simple assigning. we might leave assigning stuff for later

**Comment by zakaos** [comment]
I may have needed to set you as a collaborator before I can assign, i sent an invite to see if that fixes it.

**Comment by zakaos** [comment]
changed label to let people know this is yours :) will assign you properly when I can.

**Comment by hyeri0609** [comment]
if u need anything more on this issue? ping me

**Comment by zakaos** [comment]
I think it should function fine, im currently working on an items system that may affect the inventory, ill go ahead and close it, and make a new one if need be.
